apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: "text"
      name: "icon"
      label: "图标"

---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "radio"
      name: "enable_toc_sequence"
      label: "启用目录序号"
      help: "启用后，目录将会显示序号  // todo 配置定义，功能未实现"
      value: "true"
      options:
        - label: 启用
          value: "true"
        - label: 禁用
          value: "false"

---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: core.halo.run
    kind: PhotoGroup
  formSchema:
    - $formkit: "attachment"
      name: "cover"
      label: "分组图片"
    - $formkit: "attachment"
      name: "background"
      label: "分组顶部 banner 图片"
    - $formkit: "textarea"
      name: "description"
      label: "分组描述"

---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: core.halo.run
    kind: EquipmentGroup
  formSchema:
    - $formkit: "textarea"
      name: "description"
      label: "分组描述"

---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: core.halo.run
    kind: Equipment
  formSchema:
    - $formkit: "text"
      name: "model"
      label: "装备型号/版本"
    - $formkit: "text"
      name: "button"
      label: "左下角按钮显示文字"
      value: "详情"
    - $formkit: "text"
      name: "link"
      label: "左下角按钮跳转链接"
